plugins {
    id 'com.android.application'
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'io.github.fiadpratama.ctfapplication'
    compileSdk 34

    defaultConfig {
        applicationId "io.github.fiadpratama.ctfapplication"
        minSdk 26
        targetSdk 34
        versionCode 5
        versionName "1.5.0"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -O3 -fvisibility=hidden -fvisibility-inlines-hidden"
            }
        }
    }

    aaptOptions {
        noCompress "bin"
    }

    signingConfigs {
        release {
            storeFile file(keystoreProperties['storeFile'] ?: 'keystore.jks')
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.core:core-splashscreen:1.0.1'
}
